version: "2"
services:
  dixit:
    container_name: dixit
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "4660:4660"
    networks:
      - consul

networks:
  consul:
    external: true
